// Configuration generated by GitHub Actions - Tue May 27 10:04:07 UTC 2025
window.SUPABASE_URL = 'https://sltyrzioowontcuteqwj.supabase.co';
window.SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdHlyemlvb3dvbnRjdXRlcXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjI5OTQsImV4cCI6MjA2MzgzODk5NH0.Y2d8noHfnUSRbN1w5KJyVFTCYv33CSmTFsZ61xitakM';
